server:
  port: 8088

spring:
  config:
    import:
    - optional:classpath:/config/application-common.yml
  profiles:
    active: local
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    
admin:
  test:
    enc: ENC(9S8ZCjfbJ5dFesy2R9kghQz/8MmiGfqF)




--- #local config
spring:
  config:
    activate:
      on-profile: local
--- #dev config
spring:
  config:
    activate:
      on-profile: dev
--- #qa config
spring:
  config:
    activate:
      on-profile: qa
--- #prd config
spring:
  config:
    activate:
      on-profile: prd